### ISSUE TITLE
Заявка на изменение дизайна.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#11]
1. Поменять местами левую и правую панели (года/выпуски и тематику)
2. Убрать ISSN, передвинуть его вниз, к баннерам. Это техническая информация. (возможно, изменится впоследствии)
3. На панели "года/выпуски" добавить кнопки/ссылки над этим модулем "поиск по авторам", "поиск по статьям". Необходимый функционал реализован в ссылках "все авторы"/"все статьи". 
4. Поменять функционал и внешний вид тематик. Теперь это должны быть не кнопки, открывающие подразделы, а сами по себе разделы, открывающие списки статей. Только 4, вместо 20+. 
___________________
5. Поменять оттенок сайтов, в соответствии с новыми обложками, поставить эмблемы, новый адрес для второго ресурса (hait.opu.ua). (обложки и эмблемы прилагаются)

Количество и расположение статических страниц возможно, поменяется, а может, и нет.
По возможности, убрать флажки из выбора языков, заменить их на символы (RU,ENG,UKR), судя по всему, за флажки кое-где могут банить(?). Поменять расположение языков - ENG-UKR-RU.

**Comment by KarelWintersky** [comment]
Все кроме 

> Поменять оттенок сайтов, в соответствии с новыми обложками

**Comment by KarelWintersky** [comment]
В 70b4d5e94b6547363ea66706add49e441af7c2a7, f252d8aaad1a554b1d72ae1846c65ca8eb69193c и ранее
