### ISSUE TITLE
Максимальный размер файлов и его видимость.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#19]
Добавить в конфиг проекта значения input / max_file_size (articles.form.add.php). Добавить вывод новых лимитов загрузки на главную страницу админки (ini_get max_file_size)

**Comment by MadKitten** [comment]
Рекомендованый лимит размера файла - 3мб

**Comment by KarelWintersky** [comment]
Сделано в c448780ea095bad2ddcddaf2ca293b222ce36fc7
