### ISSUE TITLE
В списке "всех авторов" должны отображаться только авторы, у которых есть хотя бы одна статья.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#32]
Причина: требуется жесткое разделение списка редколлегии и списка авторов. Единственный способ это сделать, не ломая внутреннюю структуру, который я вижу - визуальное разделение.

**Comment by KarelWintersky** [comment]
d6f8f58d270699781808928a04506ccb57ed5c1a
568bb2efa14de5deb1c3ae0715f91ac33f4c6f46
