### ISSUE TITLE
Damage Control

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#36]
Заплаточное решение проблем, возникших в диалоге заказчика и исполнителя. Временное отключение функционала "Поиск по автору" путём замены точки входа на текущую версию "Cписок всех авторов", предназначеную для индексации.
![изображение](https://user-images.githubusercontent.com/6238683/64327805-fad83300-cfd4-11e9-8d9a-58e4f2f3dac7.png)
ЗДЕСЬ.

**Comment by KarelWintersky** [comment]
9b05f763244eb4f41aa77ccf6c7a2954eb95ecfe
