### ISSUE TITLE
Не работает кнопка "Удалить значение из базы" в разделе редактирования баннеров.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#37]
При нажатии происходит рефреш страницы, но запись остаётся на прежнем месте.

![изображение](https://user-images.githubusercontent.com/6238683/64329794-7edfea00-cfd8-11e9-968c-ddd593369ce4.png)

**Comment by KarelWintersky** [comment]
исправлено в 4c7a92440db724c14ccbe6df9e7a2f63c6d29ffb
