### ISSUE TITLE
Поле ORCID может иметь последний символ текстовый.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#39]
В частности, Х. Почему-то в системе Х, а не А было выбрано для односимвольного отображения числа 10. Необходимо рассмотреть возможность изменения типа 16ого знака на текстовый или добавить Х в список допустимых значений.

**Comment by KarelWintersky** [comment]
принято

**Comment by KarelWintersky** [comment]
исправлено в b3630f3ed475b95ddd17cf53df9e634529c8196a
