### ISSUE TITLE
Не работает редактирование, включение и выключение баннеров.

### ISSUE THREAD

**Issue by MadKitten** [KarelWintersky/LIBDb#40]
При нажатии соответствующей кнопки открывается окно редактирования, но никакие изменения при выходе из формы в базу не вносятся.

**Comment by KarelWintersky** [comment]
при выходе из формы или при сохранении?

**Comment by KarelWintersky** [comment]
принято в работу

**Comment by KarelWintersky** [comment]
Исправлено в ce7c798cc5d8a4183ff6e7015340b5badec8f435
